# Generated by Django 2.2 on 2019-12-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_category_comments_post_tag'),
    ]

    operations = [
    ]
